In [3]:
from google.cloud import bigquery

In [4]:
# Creating a Client object
client= bigquery.Client()

Using Kaggle's public dataset BigQuery integration.

In [5]:
# Create a reference to a dataset

dataset_ref = client.dataset('hacker_news', project= 'bigquery-public-data')

# get a dataset into a variable
dataset = client.get_dataset(dataset_ref)

In [6]:
# List all the tables in the "hacker_news" dataset
table_list= list(client.list_tables(dataset))
for each_table in table_list:
    print(each_table.table_id)

full

**এখন এই full টেবিল টা নিতে হবে ****

In [7]:
# প্রথমে টেবিলের রেফারেন্স তৈরি করি
table_ref= dataset_ref.table('full')
tableFull = client.get_table(table_ref)

In [8]:
tableFull.schema

[SchemaField('title', 'STRING', 'NULLABLE', None, 'Story title', (), None),
 SchemaField('url', 'STRING', 'NULLABLE', None, 'Story url', (), None),
 SchemaField('text', 'STRING', 'NULLABLE', None, 'Story or comment text', (), None),
 SchemaField('dead', 'BOOLEAN', 'NULLABLE', None, 'Is dead?', (), None),
 SchemaField('by', 'STRING', 'NULLABLE', None, "The username of the item's author.", (), None),
 SchemaField('score', 'INTEGER', 'NULLABLE', None, 'Story score', (), None),
 SchemaField('time', 'INTEGER', 'NULLABLE', None, 'Unix time', (), None),
 SchemaField('timestamp', 'TIMESTAMP', 'NULLABLE', None, 'Timestamp for the unix time', (), None),
 SchemaField('type', 'STRING', 'NULLABLE', None, 'type of details (comment comment_ranking poll story job pollopt)', (), None),
 SchemaField('id', 'INTEGER', 'NULLABLE', None, "The item's unique id.", (), None),
 SchemaField('parent', 'INTEGER', 'NULLABLE', None, 'Parent comment ID', (), None),
 SchemaField('descendants', 'INTEGER', 'NULLABLE', None, 'Number of story or poll descendants', (), None),
 SchemaField('ranking', 'INTEGER', 'NULLABLE', None, 'Comment ranking', (), None),
 SchemaField('deleted', 'BOOLEAN', 'NULLABLE', None, 'Is deleted?', (), None)]

In [13]:
columnNames= [column.name for column in tableFull.schema]
print(columnNames)

['title', 'url', 'text', 'dead', 'by', 'score', 'time', 'timestamp', 'type', 'id', 'parent', 'descendants', 'ranking', 'deleted']

In [16]:
for eachColumn in tableFull.schema: 
    print(eachColumn.name, '| ', eachColumn.field_type, '| ')

title |  STRING |
url |  STRING |
text |  STRING |
dead |  BOOLEAN |
by |  STRING |
score |  INTEGER |
time |  INTEGER |
timestamp |  TIMESTAMP |
type |  STRING |
id |  INTEGER |
parent |  INTEGER |
descendants |  INTEGER |
ranking |  INTEGER |
deleted |  BOOLEAN |

In [19]:
client.list_rows(tableFull, max_results= 7).to_dataframe()

,title,url,text,dead,by,score,time,timestamp,type,id,parent,descendants,ranking,deleted
0,None,None,None,<NA>,None,<NA>,1437658247,2015-07-23 13:30:47+00:00,story,9935559,<NA>,<NA>,<NA>,<NA>
1,None,None,None,True,None,<NA>,1437659385,2015-07-23 13:49:45+00:00,story,9935679,<NA>,<NA>,<NA>,<NA>
2,None,None,None,True,None,<NA>,1437659939,2015-07-23 13:58:59+00:00,story,9935727,<NA>,<NA>,<NA>,<NA>
3,None,None,None,<NA>,None,<NA>,1437660102,2015-07-23 14:01:42+00:00,story,9935750,<NA>,<NA>,<NA>,<NA>
4,None,None,None,<NA>,None,<NA>,1437661549,2015-07-23 14:25:49+00:00,story,9935894,<NA>,<NA>,<NA>,<NA>
5,None,None,None,<NA>,None,<NA>,1437661758,2015-07-23 14:29:18+00:00,story,9935915,<NA>,<NA>,<NA>,<NA>
6,None,None,None,True,None,<NA>,1437662737,2015-07-23 14:45:37+00:00,story,9936000,<NA>,<NA>,<NA>,<NA>

In [21]:
client.list_rows(tableFull, selected_fields=tableFull.schema[:3], max_results=5).to_dataframe()

  title   url  text
0  None  None  None
1  None  None  None
2  None  None  None
3  None  None  None
4  None  None  None